// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
............b.b..........
.....bb....bb.bbbbb......
....bbbb.bbbcccccc.....b8
cb8cc.cbbbccc8111c3....cc
cb83ccb.bc8118111c...cbbc
c8883bb.c81111cc1c..ccb8.
8cbb3...c811c1111c..ccbc.
..c113..c8111ccccc.c1dc..
..cb13..cc8ccb8888c111b..
..cc113..cbb88bbbbc11b...
...cd13..cb8888ccc11c....
...cc13c.cb88888c11cc....
....cc13cc8c1188c1cc.....
.....cc31c81111c1c.......
......c31c888cccc........
.......3ceb8cecc.........
.......3ceeeec...........
.......3ce222c...........
........c1111c...........
.......ccd11dcc..........
.......ccd11dcc..........
.......ccdd1dcc..........
.......ccd1ddcc..........
........cccccc...........
........cbbcbb...........
........ccbccc...........
.......cccbbcbc..........
......ccbbbcccb..........
......ceeecceee..........
......eeee.eeee..........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
